//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaiaProject.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GaiaProject.Resources.SharedResources.en", typeof(SharedResources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AmbasPIAbility {
            get {
                return ResourceManager.GetString("AmbasPIAbility", resourceCulture);
            }
        }
        
        internal static string AmbasSpecial {
            get {
                return ResourceManager.GetString("AmbasSpecial", resourceCulture);
            }
        }
        
        internal static string BalTakInitialAbility {
            get {
                return ResourceManager.GetString("BalTakInitialAbility", resourceCulture);
            }
        }
        
        internal static string BalTakPIAbility {
            get {
                return ResourceManager.GetString("BalTakPIAbility", resourceCulture);
            }
        }
        
        internal static string BalTakSpecial {
            get {
                return ResourceManager.GetString("BalTakSpecial", resourceCulture);
            }
        }
        
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string FiraksPIAbility {
            get {
                return ResourceManager.GetString("FiraksPIAbility", resourceCulture);
            }
        }
        
        internal static string FiraksSpecial {
            get {
                return ResourceManager.GetString("FiraksSpecial", resourceCulture);
            }
        }
        
        internal static string GeodenPIAbility {
            get {
                return ResourceManager.GetString("GeodenPIAbility", resourceCulture);
            }
        }
        
        internal static string GleenInitialAbility {
            get {
                return ResourceManager.GetString("GleenInitialAbility", resourceCulture);
            }
        }
        
        internal static string GleenPIAbility {
            get {
                return ResourceManager.GetString("GleenPIAbility", resourceCulture);
            }
        }
        
        internal static string GleenSpecial {
            get {
                return ResourceManager.GetString("GleenSpecial", resourceCulture);
            }
        }
        
        internal static string HadschHallaPIAbility {
            get {
                return ResourceManager.GetString("HadschHallaPIAbility", resourceCulture);
            }
        }
        
        internal static string HadschHallaSpecial {
            get {
                return ResourceManager.GetString("HadschHallaSpecial", resourceCulture);
            }
        }
        
        internal static string HiveInitialAbility {
            get {
                return ResourceManager.GetString("HiveInitialAbility", resourceCulture);
            }
        }
        
        internal static string HivePIAbility {
            get {
                return ResourceManager.GetString("HivePIAbility", resourceCulture);
            }
        }
        
        internal static string HiveSpecial {
            get {
                return ResourceManager.GetString("HiveSpecial", resourceCulture);
            }
        }
        
        internal static string ItarInitialAbility {
            get {
                return ResourceManager.GetString("ItarInitialAbility", resourceCulture);
            }
        }
        
        internal static string ItarPIAbility {
            get {
                return ResourceManager.GetString("ItarPIAbility", resourceCulture);
            }
        }
        
        internal static string ItarSpecial {
            get {
                return ResourceManager.GetString("ItarSpecial", resourceCulture);
            }
        }
        
        internal static string LantidsInitialAbility {
            get {
                return ResourceManager.GetString("LantidsInitialAbility", resourceCulture);
            }
        }
        
        internal static string LantidsPIAbility {
            get {
                return ResourceManager.GetString("LantidsPIAbility", resourceCulture);
            }
        }
        
        internal static string LantidsSpecial {
            get {
                return ResourceManager.GetString("LantidsSpecial", resourceCulture);
            }
        }
        
        internal static string MadAndroidInitialability {
            get {
                return ResourceManager.GetString("MadAndroidInitialability", resourceCulture);
            }
        }
        
        internal static string MadAndroidPIAbility {
            get {
                return ResourceManager.GetString("MadAndroidPIAbility", resourceCulture);
            }
        }
        
        internal static string MadAndroidSpecial {
            get {
                return ResourceManager.GetString("MadAndroidSpecial", resourceCulture);
            }
        }
        
        internal static string NevlaInitialAbility {
            get {
                return ResourceManager.GetString("NevlaInitialAbility", resourceCulture);
            }
        }
        
        internal static string NevlaPIAbility {
            get {
                return ResourceManager.GetString("NevlaPIAbility", resourceCulture);
            }
        }
        
        internal static string NevlaSpecial {
            get {
                return ResourceManager.GetString("NevlaSpecial", resourceCulture);
            }
        }
        
        internal static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        internal static string TaklonsInitialAbility {
            get {
                return ResourceManager.GetString("TaklonsInitialAbility", resourceCulture);
            }
        }
        
        internal static string TaklonsPIAbility {
            get {
                return ResourceManager.GetString("TaklonsPIAbility", resourceCulture);
            }
        }
        
        internal static string TerranerInitialAbility {
            get {
                return ResourceManager.GetString("TerranerInitialAbility", resourceCulture);
            }
        }
        
        internal static string TerranerPIAbility {
            get {
                return ResourceManager.GetString("TerranerPIAbility", resourceCulture);
            }
        }
        
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        internal static string XenosInitialAbility {
            get {
                return ResourceManager.GetString("XenosInitialAbility", resourceCulture);
            }
        }
        
        internal static string XenosPIAbility {
            get {
                return ResourceManager.GetString("XenosPIAbility", resourceCulture);
            }
        }
        
        internal static string XenosSpecial {
            get {
                return ResourceManager.GetString("XenosSpecial", resourceCulture);
            }
        }
        
        internal static string 上一步 {
            get {
                return ResourceManager.GetString("上一步", resourceCulture);
            }
        }
        
        internal static string 上次行动时间 {
            get {
                return ResourceManager.GetString("上次行动时间", resourceCulture);
            }
        }
        
        internal static string 下一步 {
            get {
                return ResourceManager.GetString("下一步", resourceCulture);
            }
        }
        
        internal static string 下回合收入 {
            get {
                return ResourceManager.GetString("下回合收入", resourceCulture);
            }
        }
        
        internal static string 主城等级 {
            get {
                return ResourceManager.GetString("主城等级", resourceCulture);
            }
        }
        
        internal static string 亚特兰斯星人 {
            get {
                return ResourceManager.GetString("亚特兰斯星人", resourceCulture);
            }
        }
        
        internal static string 人工智能 {
            get {
                return ResourceManager.GetString("人工智能", resourceCulture);
            }
        }
        
        internal static string 人数 {
            get {
                return ResourceManager.GetString("人数", resourceCulture);
            }
        }
        
        internal static string 人类 {
            get {
                return ResourceManager.GetString("人类", resourceCulture);
            }
        }
        
        internal static string 人类正常使用Convert命令_一次只能转换一种资源 {
            get {
                return ResourceManager.GetString("人类正常使用Convert命令 一次只能转换一种资源", resourceCulture);
            }
        }
        
        internal static string 从服务器恢复所有游戏 {
            get {
                return ResourceManager.GetString("从服务器恢复所有游戏", resourceCulture);
            }
        }
        
        internal static string 伊塔星人 {
            get {
                return ResourceManager.GetString("伊塔星人", resourceCulture);
            }
        }
        
        internal static string 你的游戏 {
            get {
                return ResourceManager.GetString("你的游戏", resourceCulture);
            }
        }
        
        internal static string 使用 {
            get {
                return ResourceManager.GetString("使用", resourceCulture);
            }
        }
        
        internal static string 使用已有账户登录 {
            get {
                return ResourceManager.GetString("使用已有账户登录", resourceCulture);
            }
        }
        
        internal static string 使用智慧石指令示例 {
            get {
                return ResourceManager.GetString("使用智慧石指令示例", resourceCulture);
            }
        }
        
        internal static string 使用种族 {
            get {
                return ResourceManager.GetString("使用种族", resourceCulture);
            }
        }
        
        internal static string 保存 {
            get {
                return ResourceManager.GetString("保存", resourceCulture);
            }
        }
        
        internal static string 保存成功 {
            get {
                return ResourceManager.GetString("保存成功", resourceCulture);
            }
        }
        
        internal static string 信用点 {
            get {
                return ResourceManager.GetString("信用点", resourceCulture);
            }
        }
        
        internal static string 修改信息 {
            get {
                return ResourceManager.GetString("修改信息", resourceCulture);
            }
        }
        
        internal static string 修改密码 {
            get {
                return ResourceManager.GetString("修改密码", resourceCulture);
            }
        }
        
        internal static string 做Gaia行动 {
            get {
                return ResourceManager.GetString("做Gaia行动", resourceCulture);
            }
        }
        
        internal static string 允许观看_其他玩家可以查看_ {
            get {
                return ResourceManager.GetString("允许观看(其他玩家可以查看)", resourceCulture);
            }
        }
        
        internal static string 先增加能量 {
            get {
                return ResourceManager.GetString("先增加能量", resourceCulture);
            }
        }
        
        internal static string 全部 {
            get {
                return ResourceManager.GetString("全部", resourceCulture);
            }
        }
        
        internal static string 全部兑换信用点 {
            get {
                return ResourceManager.GetString("全部兑换信用点", resourceCulture);
            }
        }
        
        internal static string 全部种族 {
            get {
                return ResourceManager.GetString("全部种族", resourceCulture);
            }
        }
        
        internal static string 公开游戏 {
            get {
                return ResourceManager.GetString("公开游戏", resourceCulture);
            }
        }
        
        internal static string 关闭 {
            get {
                return ResourceManager.GetString("关闭", resourceCulture);
            }
        }
        
        internal static string 关闭全部回合提示 {
            get {
                return ResourceManager.GetString("关闭全部回合提示", resourceCulture);
            }
        }
        
        internal static string 启用全部回合提示 {
            get {
                return ResourceManager.GetString("启用全部回合提示", resourceCulture);
            }
        }
        
        internal static string 冰雪 {
            get {
                return ResourceManager.GetString("冰雪", resourceCulture);
            }
        }
        
        internal static string 出场率 {
            get {
                return ResourceManager.GetString("出场率", resourceCulture);
            }
        }
        
        internal static string 分数 {
            get {
                return ResourceManager.GetString("分数", resourceCulture);
            }
        }
        
        internal static string 创建 {
            get {
                return ResourceManager.GetString("创建", resourceCulture);
            }
        }
        
        internal static string 创建一个新的账户_ {
            get {
                return ResourceManager.GetString("创建一个新的账户?", resourceCulture);
            }
        }
        
        internal static string 创建房间 {
            get {
                return ResourceManager.GetString("创建房间", resourceCulture);
            }
        }
        
        internal static string 创建新的房间 {
            get {
                return ResourceManager.GetString("创建新的房间", resourceCulture);
            }
        }
        
        internal static string 初始星球颜色 {
            get {
                return ResourceManager.GetString("初始星球颜色", resourceCulture);
            }
        }
        
        internal static string 初始研究 {
            get {
                return ResourceManager.GetString("初始研究", resourceCulture);
            }
        }
        
        internal static string 删除所有游戏 {
            get {
                return ResourceManager.GetString("删除所有游戏", resourceCulture);
            }
        }
        
        internal static string 利爪族 {
            get {
                return ResourceManager.GetString("利爪族", resourceCulture);
            }
        }
        
        internal static string 前 {
            get {
                return ResourceManager.GetString("前", resourceCulture);
            }
        }
        
        internal static string 即时刷新_需要浏览器支持websocket_ {
            get {
                return ResourceManager.GetString("即时刷新(需要浏览器支持websocket)", resourceCulture);
            }
        }
        
        internal static string 双人变体固定 {
            get {
                return ResourceManager.GetString("双人变体固定", resourceCulture);
            }
        }
        
        internal static string 双人固定 {
            get {
                return ResourceManager.GetString("双人固定", resourceCulture);
            }
        }
        
        internal static string 双人随机 {
            get {
                return ResourceManager.GetString("双人随机", resourceCulture);
            }
        }
        
        internal static string 取消 {
            get {
                return ResourceManager.GetString("取消", resourceCulture);
            }
        }
        
        internal static string 变化数值 {
            get {
                return ResourceManager.GetString("变化数值", resourceCulture);
            }
        }
        
        internal static string 后 {
            get {
                return ResourceManager.GetString("后", resourceCulture);
            }
        }
        
        internal static string 否 {
            get {
                return ResourceManager.GetString("否", resourceCulture);
            }
        }
        
        internal static string 吸取 {
            get {
                return ResourceManager.GetString("吸取", resourceCulture);
            }
        }
        
        internal static string 命令 {
            get {
                return ResourceManager.GetString("命令", resourceCulture);
            }
        }
        
        internal static string 双人变体随机 {
            get {
                return ResourceManager.GetString("双人变体随机", resourceCulture);
            }
        }
        
        internal static string 四人固定 {
            get {
                return ResourceManager.GetString("四人固定", resourceCulture);
            }
        }
        
        internal static string 四人完全随机 {
            get {
                return ResourceManager.GetString("四人完全随机", resourceCulture);
            }
        }
        
        internal static string 四人部分随机 {
            get {
                return ResourceManager.GetString("四人部分随机", resourceCulture);
            }
        }
        
        internal static string 回合 {
            get {
                return ResourceManager.GetString("回合", resourceCulture);
            }
        }
        
        internal static string 回合助推板 {
            get {
                return ResourceManager.GetString("回合助推板", resourceCulture);
            }
        }
        
        internal static string 回合提示 {
            get {
                return ResourceManager.GetString("回合提示", resourceCulture);
            }
        }
        
        internal static string 回合操作 {
            get {
                return ResourceManager.GetString("回合操作", resourceCulture);
            }
        }
        
        internal static string 回合结束计分 {
            get {
                return ResourceManager.GetString("回合结束计分", resourceCulture);
            }
        }
        
        internal static string 圣禽族 {
            get {
                return ResourceManager.GetString("圣禽族", resourceCulture);
            }
        }
        
        internal static string 地图选择 {
            get {
                return ResourceManager.GetString("地图选择", resourceCulture);
            }
        }
        
        internal static string 地形改造 {
            get {
                return ResourceManager.GetString("地形改造", resourceCulture);
            }
        }
        
        internal static string 基础科技 {
            get {
                return ResourceManager.GetString("基础科技", resourceCulture);
            }
        }
        
        internal static string 备份所有游戏 {
            get {
                return ResourceManager.GetString("备份所有游戏", resourceCulture);
            }
        }
        
        internal static string 备忘 {
            get {
                return ResourceManager.GetString("备忘", resourceCulture);
            }
        }
        
        internal static string 大使星人 {
            get {
                return ResourceManager.GetString("大使星人", resourceCulture);
            }
        }
        
        internal static string 密码 {
            get {
                return ResourceManager.GetString("密码", resourceCulture);
            }
        }
        
        internal static string 对局记录 {
            get {
                return ResourceManager.GetString("对局记录", resourceCulture);
            }
        }
        
        internal static string 局数 {
            get {
                return ResourceManager.GetString("局数", resourceCulture);
            }
        }
        
        internal static string 帮助 {
            get {
                return ResourceManager.GetString("帮助", resourceCulture);
            }
        }
        
        internal static string 使用帮助 {
            get {
                return ResourceManager.GetString("使用帮助", resourceCulture);
            }
        }
        
        internal static string 种族介绍 {
            get {
                return ResourceManager.GetString("种族介绍", resourceCulture);
            }
        }
        
        internal static string 建议和反馈 {
            get {
                return ResourceManager.GetString("建议和反馈", resourceCulture);
            }
        }
        
        internal static string 玩家统计 {
            get {
                return ResourceManager.GetString("玩家统计", resourceCulture);
            }
        }
        
        internal static string 种族高分 {
            get {
                return ResourceManager.GetString("种族高分", resourceCulture);
            }
        }
        
        internal static string 种族统计 {
            get {
                return ResourceManager.GetString("种族统计", resourceCulture);
            }
        }
        
        internal static string 种族胜率 {
            get {
                return ResourceManager.GetString("种族胜率", resourceCulture);
            }
        }
        
        internal static string 科技版 {
            get {
                return ResourceManager.GetString("科技版", resourceCulture);
            }
        }
        
        internal static string 平均分 {
            get {
                return ResourceManager.GetString("平均分", resourceCulture);
            }
        }
        
        internal static string 建造初始房子 {
            get {
                return ResourceManager.GetString("建造初始房子", resourceCulture);
            }
        }
        
        internal static string 异空族 {
            get {
                return ResourceManager.GetString("异空族", resourceCulture);
            }
        }
        
        internal static string 当前回合玩家 {
            get {
                return ResourceManager.GetString("当前回合玩家", resourceCulture);
            }
        }
        
        internal static string 快速行动 {
            get {
                return ResourceManager.GetString("快速行动", resourceCulture);
            }
        }
        
        internal static string 恢复单个游戏 {
            get {
                return ResourceManager.GetString("恢复单个游戏", resourceCulture);
            }
        }
        
        internal static string 恢复所有游戏 {
            get {
                return ResourceManager.GetString("恢复所有游戏", resourceCulture);
            }
        }
        
        internal static string 或 {
            get {
                return ResourceManager.GetString("或", resourceCulture);
            }
        }
        
        internal static string 房间 {
            get {
                return ResourceManager.GetString("房间", resourceCulture);
            }
        }
        
        internal static string 房间名称 {
            get {
                return ResourceManager.GetString("房间名称", resourceCulture);
            }
        }
        
        internal static string 玩家人数 {
            get {
                return ResourceManager.GetString("玩家人数", resourceCulture);
            }
        }
        
        internal static string 游戏说明 {
            get {
                return ResourceManager.GetString("游戏说明", resourceCulture);
            }
        }
        
        internal static string 手动输入 {
            get {
                return ResourceManager.GetString("手动输入", resourceCulture);
            }
        }
        
        internal static string 执行并结束 {
            get {
                return ResourceManager.GetString("执行并结束", resourceCulture);
            }
        }
        
        internal static string 找回密码_ {
            get {
                return ResourceManager.GetString("找回密码?", resourceCulture);
            }
        }
        
        internal static string 折叠科技 {
            get {
                return ResourceManager.GetString("折叠科技", resourceCulture);
            }
        }
        
        internal static string 换取知识 {
            get {
                return ResourceManager.GetString("换取知识", resourceCulture);
            }
        }
        
        internal static string 提示 {
            get {
                return ResourceManager.GetString("提示", resourceCulture);
            }
        }
        
        internal static string 提示信息 {
            get {
                return ResourceManager.GetString("提示信息", resourceCulture);
            }
        }
        
        internal static string 放置黑星 {
            get {
                return ResourceManager.GetString("放置黑星", resourceCulture);
            }
        }
        
        internal static string 数量 {
            get {
                return ResourceManager.GetString("数量", resourceCulture);
            }
        }
        
        internal static string 旋转地图 {
            get {
                return ResourceManager.GetString("旋转地图", resourceCulture);
            }
        }
        
        internal static string 旋转地图_随机模式下尾家旋转_ {
            get {
                return ResourceManager.GetString("旋转地图(随机模式下尾家旋转)", resourceCulture);
            }
        }
        
        internal static string 旋转步数 {
            get {
                return ResourceManager.GetString("旋转步数", resourceCulture);
            }
        }
        
        internal static string 无 {
            get {
                return ResourceManager.GetString("无", resourceCulture);
            }
        }
        
        internal static string 时常 {
            get {
                return ResourceManager.GetString("时常", resourceCulture);
            }
        }
        
        internal static string 星域 {
            get {
                return ResourceManager.GetString("星域", resourceCulture);
            }
        }
        
        internal static string 星域板块 {
            get {
                return ResourceManager.GetString("星域板块", resourceCulture);
            }
        }
        
        internal static string 星球 {
            get {
                return ResourceManager.GetString("星球", resourceCulture);
            }
        }
        
        internal static string 星球种类 {
            get {
                return ResourceManager.GetString("星球种类", resourceCulture);
            }
        }
        
        internal static string 星际要塞能力 {
            get {
                return ResourceManager.GetString("星际要塞能力", resourceCulture);
            }
        }
        
        internal static string 星际要塞行动指令示例 {
            get {
                return ResourceManager.GetString("星际要塞行动指令示例", resourceCulture);
            }
        }
        
        internal static string 是 {
            get {
                return ResourceManager.GetString("是", resourceCulture);
            }
        }
        
        internal static string 是否为测试局 {
            get {
                return ResourceManager.GetString("是否为测试局", resourceCulture);
            }
        }
        
        internal static string 是否要从 {
            get {
                return ResourceManager.GetString("是否要从", resourceCulture);
            }
        }
        
        internal static string 显示全部日志 {
            get {
                return ResourceManager.GetString("显示全部日志", resourceCulture);
            }
        }
        
        internal static string 晶矿星人 {
            get {
                return ResourceManager.GetString("晶矿星人", resourceCulture);
            }
        }
        
        internal static string 智慧石所在区域 {
            get {
                return ResourceManager.GetString("智慧石所在区域", resourceCulture);
            }
        }
        
        internal static string 暂无对局 {
            get {
                return ResourceManager.GetString("暂无对局", resourceCulture);
            }
        }
        
        internal static string 最低分 {
            get {
                return ResourceManager.GetString("最低分", resourceCulture);
            }
        }
        
        internal static string 最高分 {
            get {
                return ResourceManager.GetString("最高分", resourceCulture);
            }
        }
        
        internal static string 未使用 {
            get {
                return ResourceManager.GetString("未使用", resourceCulture);
            }
        }
        
        internal static string 查看好友 {
            get {
                return ResourceManager.GetString("查看好友", resourceCulture);
            }
        }
        
        internal static string 格伦星人 {
            get {
                return ResourceManager.GetString("格伦星人", resourceCulture);
            }
        }
        
        internal static string 棕色 {
            get {
                return ResourceManager.GetString("棕色", resourceCulture);
            }
        }
        
        internal static string 橙色 {
            get {
                return ResourceManager.GetString("橙色", resourceCulture);
            }
        }
        
        internal static string 次数 {
            get {
                return ResourceManager.GetString("次数", resourceCulture);
            }
        }
        
        internal static string 欢迎 {
            get {
                return ResourceManager.GetString("欢迎", resourceCulture);
            }
        }
        
        internal static string 氧化 {
            get {
                return ResourceManager.GetString("氧化", resourceCulture);
            }
        }
        
        internal static string 沙漠 {
            get {
                return ResourceManager.GetString("沙漠", resourceCulture);
            }
        }
        
        internal static string 沼泽 {
            get {
                return ResourceManager.GetString("沼泽", resourceCulture);
            }
        }
        
        internal static string 注 {
            get {
                return ResourceManager.GetString("注", resourceCulture);
            }
        }
        
        internal static string 注册 {
            get {
                return ResourceManager.GetString("注册", resourceCulture);
            }
        }
        
        internal static string 游戏结束 {
            get {
                return ResourceManager.GetString("游戏结束", resourceCulture);
            }
        }
        
        internal static string 灰色 {
            get {
                return ResourceManager.GetString("灰色", resourceCulture);
            }
        }
        
        internal static string 点能量 {
            get {
                return ResourceManager.GetString("点能量", resourceCulture);
            }
        }
        
        internal static string 炽炎族 {
            get {
                return ResourceManager.GetString("炽炎族", resourceCulture);
            }
        }
        
        internal static string 熔岩 {
            get {
                return ResourceManager.GetString("熔岩", resourceCulture);
            }
        }
        
        internal static string 版本 {
            get {
                return ResourceManager.GetString("版本", resourceCulture);
            }
        }
        
        internal static string 特权 {
            get {
                return ResourceManager.GetString("特权", resourceCulture);
            }
        }
        
        internal static string 特殊 {
            get {
                return ResourceManager.GetString("特殊", resourceCulture);
            }
        }
        
        internal static string 牺牲能量 {
            get {
                return ResourceManager.GetString("牺牲能量", resourceCulture);
            }
        }
        
        internal static string 玩家 {
            get {
                return ResourceManager.GetString("玩家", resourceCulture);
            }
        }
        
        internal static string 玩家1 {
            get {
                return ResourceManager.GetString("玩家1", resourceCulture);
            }
        }
        
        internal static string 玩家2 {
            get {
                return ResourceManager.GetString("玩家2", resourceCulture);
            }
        }
        
        internal static string 玩家3 {
            get {
                return ResourceManager.GetString("玩家3", resourceCulture);
            }
        }
        
        internal static string 玩家4 {
            get {
                return ResourceManager.GetString("玩家4", resourceCulture);
            }
        }
        
        internal static string 玩家顺序是 {
            get {
                return ResourceManager.GetString("玩家顺序是", resourceCulture);
            }
        }
        
        internal static string 现在是 {
            get {
                return ResourceManager.GetString("现在是", resourceCulture);
            }
        }
        
        internal static string 现在等待 {
            get {
                return ResourceManager.GetString("现在等待", resourceCulture);
            }
        }
        
        internal static string 用户名 {
            get {
                return ResourceManager.GetString("用户名", resourceCulture);
            }
        }
        
        internal static string 疯狂机器 {
            get {
                return ResourceManager.GetString("疯狂机器", resourceCulture);
            }
        }
        
        internal static string 登录 {
            get {
                return ResourceManager.GetString("登录", resourceCulture);
            }
        }
        
        internal static string 白色 {
            get {
                return ResourceManager.GetString("白色", resourceCulture);
            }
        }
        
        internal static string 的回合 {
            get {
                return ResourceManager.GetString("的回合", resourceCulture);
            }
        }
        
        internal static string 盖亚区盖亚数量 {
            get {
                return ResourceManager.GetString("盖亚区盖亚数量", resourceCulture);
            }
        }
        
        internal static string 盖亚计划 {
            get {
                return ResourceManager.GetString("盖亚计划", resourceCulture);
            }
        }
        
        internal static string 盖亚阶段指令示例 {
            get {
                return ResourceManager.GetString("盖亚阶段指令示例", resourceCulture);
            }
        }
        
        internal static string Window_OpenMap_Info {
            get {
                return ResourceManager.GetString("Window_OpenMap_Info", resourceCulture);
            }
        }
        
        internal static string 知识 {
            get {
                return ResourceManager.GetString("知识", resourceCulture);
            }
        }
        
        internal static string 矿 {
            get {
                return ResourceManager.GetString("矿", resourceCulture);
            }
        }
        
        internal static string 确定 {
            get {
                return ResourceManager.GetString("确定", resourceCulture);
            }
        }
        
        internal static string 确定升级 {
            get {
                return ResourceManager.GetString("确定升级", resourceCulture);
            }
        }
        
        internal static string 确定旋转 {
            get {
                return ResourceManager.GetString("确定旋转", resourceCulture);
            }
        }
        
        internal static string 确认 {
            get {
                return ResourceManager.GetString("确认", resourceCulture);
            }
        }
        
        internal static string 种族 {
            get {
                return ResourceManager.GetString("种族", resourceCulture);
            }
        }
        
        internal static string 种族初始能力 {
            get {
                return ResourceManager.GetString("种族初始能力", resourceCulture);
            }
        }
        
        internal static string 种族名 {
            get {
                return ResourceManager.GetString("种族名", resourceCulture);
            }
        }
        
        internal static string 科学 {
            get {
                return ResourceManager.GetString("科学", resourceCulture);
            }
        }
        
        internal static string 科技 {
            get {
                return ResourceManager.GetString("科技", resourceCulture);
            }
        }
        
        internal static string 科技总分 {
            get {
                return ResourceManager.GetString("科技总分", resourceCulture);
            }
        }
        
        internal static string 立即执行 {
            get {
                return ResourceManager.GetString("立即执行", resourceCulture);
            }
        }
        
        internal static string 章鱼人 {
            get {
                return ResourceManager.GetString("章鱼人", resourceCulture);
            }
        }
        
        internal static string 等待以下吸取能量 {
            get {
                return ResourceManager.GetString("等待以下吸取能量", resourceCulture);
            }
        }
        
        internal static string 等待删除游戏 {
            get {
                return ResourceManager.GetString("等待删除游戏", resourceCulture);
            }
        }
        
        internal static string 等待玩家 {
            get {
                return ResourceManager.GetString("等待玩家", resourceCulture);
            }
        }
        
        internal static string 管理 {
            get {
                return ResourceManager.GetString("管理", resourceCulture);
            }
        }
        
        internal static string 管理游戏 {
            get {
                return ResourceManager.GetString("管理游戏", resourceCulture);
            }
        }
        
        internal static string 红色 {
            get {
                return ResourceManager.GetString("红色", resourceCulture);
            }
        }
        
        internal static string 终局计分板 {
            get {
                return ResourceManager.GetString("终局计分板", resourceCulture);
            }
        }
        
        internal static string 经济 {
            get {
                return ResourceManager.GetString("经济", resourceCulture);
            }
        }
        
        internal static string 结局总计分 {
            get {
                return ResourceManager.GetString("结局总计分", resourceCulture);
            }
        }
        
        internal static string 结束操作 {
            get {
                return ResourceManager.GetString("结束操作", resourceCulture);
            }
        }
        
        internal static string 结束旋转 {
            get {
                return ResourceManager.GetString("结束旋转", resourceCulture);
            }
        }
        
        internal static string 结束游戏 {
            get {
                return ResourceManager.GetString("结束游戏", resourceCulture);
            }
        }
        
        internal static string 统计 {
            get {
                return ResourceManager.GetString("统计", resourceCulture);
            }
        }
        
        internal static string 联邦板块 {
            get {
                return ResourceManager.GetString("联邦板块", resourceCulture);
            }
        }
        
        internal static string 胜场 {
            get {
                return ResourceManager.GetString("胜场", resourceCulture);
            }
        }
        
        internal static string 胜率 {
            get {
                return ResourceManager.GetString("胜率", resourceCulture);
            }
        }
        
        internal static string 能力是否使用 {
            get {
                return ResourceManager.GetString("能力是否使用", resourceCulture);
            }
        }
        
        internal static string 能量 {
            get {
                return ResourceManager.GetString("能量", resourceCulture);
            }
        }
        
        internal static string 航行 {
            get {
                return ResourceManager.GetString("航行", resourceCulture);
            }
        }
        
        internal static string 获取所有游戏列表 {
            get {
                return ResourceManager.GetString("获取所有游戏列表", resourceCulture);
            }
        }
        
        internal static string 蓝色 {
            get {
                return ResourceManager.GetString("蓝色", resourceCulture);
            }
        }
        
        internal static string 虚拟玩家 {
            get {
                return ResourceManager.GetString("虚拟玩家", resourceCulture);
            }
        }
        
        internal static string 蜂人 {
            get {
                return ResourceManager.GetString("蜂人", resourceCulture);
            }
        }
        
        internal static string 行动区域 {
            get {
                return ResourceManager.GetString("行动区域", resourceCulture);
            }
        }
        
        internal static string 被覆盖的科技 {
            get {
                return ResourceManager.GetString("被覆盖的科技", resourceCulture);
            }
        }
        
        internal static string 要塞行动 {
            get {
                return ResourceManager.GetString("要塞行动", resourceCulture);
            }
        }
        
        internal static string 记住我_ {
            get {
                return ResourceManager.GetString("记住我?", resourceCulture);
            }
        }
        
        internal static string 语句 {
            get {
                return ResourceManager.GetString("语句", resourceCulture);
            }
        }
        
        internal static string 请先登录 {
            get {
                return ResourceManager.GetString("请先登录", resourceCulture);
            }
        }
        
        internal static string 请先选择联邦板块 {
            get {
                return ResourceManager.GetString("请先选择联邦板块", resourceCulture);
            }
        }
        
        internal static string 请选择位置 {
            get {
                return ResourceManager.GetString("请选择位置", resourceCulture);
            }
        }
        
        internal static string 请选择升级科技 {
            get {
                return ResourceManager.GetString("请选择升级科技", resourceCulture);
            }
        }
        
        internal static string 请选择回合助推板 {
            get {
                return ResourceManager.GetString("请选择回合助推板", resourceCulture);
            }
        }
        
        internal static string 请选择科技板块 {
            get {
                return ResourceManager.GetString("请选择科技板块", resourceCulture);
            }
        }
        
        internal static string 请选择联邦板块 {
            get {
                return ResourceManager.GetString("请选择联邦板块", resourceCulture);
            }
        }
        
        internal static string 请选择被覆盖科技 {
            get {
                return ResourceManager.GetString("请选择被覆盖科技", resourceCulture);
            }
        }
        
        internal static string 请选择高级科技 {
            get {
                return ResourceManager.GetString("请选择高级科技", resourceCulture);
            }
        }
        
        internal static string 资源总分 {
            get {
                return ResourceManager.GetString("资源总分", resourceCulture);
            }
        }
        
        internal static string 超星人 {
            get {
                return ResourceManager.GetString("超星人", resourceCulture);
            }
        }
        
        internal static string 跳过回合玩家 {
            get {
                return ResourceManager.GetString("跳过回合玩家", resourceCulture);
            }
        }
        
        internal static string 进入第六回合 {
            get {
                return ResourceManager.GetString("进入第六回合", resourceCulture);
            }
        }
        
        internal static string 进入管理后台 {
            get {
                return ResourceManager.GetString("进入管理后台", resourceCulture);
            }
        }
        
        internal static string 退出 {
            get {
                return ResourceManager.GetString("退出", resourceCulture);
            }
        }
        
        internal static string 逆时针 {
            get {
                return ResourceManager.GetString("逆时针", resourceCulture);
            }
        }
        
        internal static string 选择助推板 {
            get {
                return ResourceManager.GetString("选择助推板", resourceCulture);
            }
        }
        
        internal static string 选择回合助推板 {
            get {
                return ResourceManager.GetString("选择回合助推板", resourceCulture);
            }
        }
        
        internal static string 选择好友 {
            get {
                return ResourceManager.GetString("选择好友", resourceCulture);
            }
        }
        
        internal static string 选择想要的能量分配方式 {
            get {
                return ResourceManager.GetString("选择想要的能量分配方式", resourceCulture);
            }
        }
        
        internal static string 选择科技版 {
            get {
                return ResourceManager.GetString("选择科技版", resourceCulture);
            }
        }
        
        internal static string 选择联邦位置 {
            get {
                return ResourceManager.GetString("选择联邦位置", resourceCulture);
            }
        }
        
        internal static string 选择联邦板块 {
            get {
                return ResourceManager.GetString("选择联邦板块", resourceCulture);
            }
        }
        
        internal static string 选择要升级的建筑 {
            get {
                return ResourceManager.GetString("选择要升级的建筑", resourceCulture);
            }
        }
        
        internal static string 选种族 {
            get {
                return ResourceManager.GetString("选种族", resourceCulture);
            }
        }
        
        internal static string 重置操作 {
            get {
                return ResourceManager.GetString("重置操作", resourceCulture);
            }
        }
        
        internal static string 量子魔方 {
            get {
                return ResourceManager.GetString("量子魔方", resourceCulture);
            }
        }
        
        internal static string 钛金 {
            get {
                return ResourceManager.GetString("钛金", resourceCulture);
            }
        }
        
        internal static string 陆地 {
            get {
                return ResourceManager.GetString("陆地", resourceCulture);
            }
        }
        
        internal static string 随机顺位 {
            get {
                return ResourceManager.GetString("随机顺位", resourceCulture);
            }
        }
        
        internal static string 顺时针 {
            get {
                return ResourceManager.GetString("顺时针", resourceCulture);
            }
        }
        
        internal static string 颜色是 {
            get {
                return ResourceManager.GetString("颜色是", resourceCulture);
            }
        }
        
        internal static string 高级科技 {
            get {
                return ResourceManager.GetString("高级科技", resourceCulture);
            }
        }
        
        internal static string 黄色 {
            get {
                return ResourceManager.GetString("黄色", resourceCulture);
            }
        }
        
        internal static string 现在是Round {
            get {
                return ResourceManager.GetString("现在是Round", resourceCulture);
            }
        }
        
        internal static string 创建大厅房间 {
            get {
                return ResourceManager.GetString("创建大厅房间", resourceCulture);
            }
        }
        
        internal static string 地图模式 {
            get {
                return ResourceManager.GetString("地图模式", resourceCulture);
            }
        }
        
        internal static string 禁止种族 {
            get {
                return ResourceManager.GetString("禁止种族", resourceCulture);
            }
        }
        
        internal static string _0__是否要从__1__吸取__2__点能量 {
            get {
                return ResourceManager.GetString("{0} 是否要从 {1} 吸取 {2} 点能量", resourceCulture);
            }
        }
        
        internal static string 大厅 {
            get {
                return ResourceManager.GetString("大厅", resourceCulture);
            }
        }
        
        internal static string 讨论 {
            get {
                return ResourceManager.GetString("讨论", resourceCulture);
            }
        }
        
        internal static string 提交反馈 {
            get {
                return ResourceManager.GetString("提交反馈", resourceCulture);
            }
        }
        
        internal static string 发布文章 {
            get {
                return ResourceManager.GetString("发布文章", resourceCulture);
            }
        }
        
        internal static string Forum_Feedback_Notice {
            get {
                return ResourceManager.GetString("Forum_Feedback_Notice", resourceCulture);
            }
        }
        
        internal static string Forum_Article_Notice {
            get {
                return ResourceManager.GetString("Forum_Article_Notice", resourceCulture);
            }
        }
        
        internal static string Forum_Article_Title {
            get {
                return ResourceManager.GetString("Forum_Article_Title", resourceCulture);
            }
        }
        
        internal static string Forum_Article_Author {
            get {
                return ResourceManager.GetString("Forum_Article_Author", resourceCulture);
            }
        }
        
        internal static string Forum_Article_Time {
            get {
                return ResourceManager.GetString("Forum_Article_Time", resourceCulture);
            }
        }
        
        internal static string Forum_Article_Operate {
            get {
                return ResourceManager.GetString("Forum_Article_Operate", resourceCulture);
            }
        }
        
        internal static string Forum_Article_Contents {
            get {
                return ResourceManager.GetString("Forum_Article_Contents", resourceCulture);
            }
        }
        
        internal static string Forum_Article_Save {
            get {
                return ResourceManager.GetString("Forum_Article_Save", resourceCulture);
            }
        }
        
        internal static string Forum_Article_List {
            get {
                return ResourceManager.GetString("Forum_Article_List", resourceCulture);
            }
        }
        
        internal static string changelanguage {
            get {
                return ResourceManager.GetString("changelanguage", resourceCulture);
            }
        }
        
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        internal static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        internal static string 比赛列表 {
            get {
                return ResourceManager.GetString("比赛列表", resourceCulture);
            }
        }
        
        internal static string Match_Index_Info {
            get {
                return ResourceManager.GetString("Match_Index_Info", resourceCulture);
            }
        }
        
        internal static string Match_Index_Title {
            get {
                return ResourceManager.GetString("Match_Index_Title", resourceCulture);
            }
        }
        
        internal static string Match_Index_PlayersNum {
            get {
                return ResourceManager.GetString("Match_Index_PlayersNum", resourceCulture);
            }
        }
        
        internal static string Match_Index_GamesNum {
            get {
                return ResourceManager.GetString("Match_Index_GamesNum", resourceCulture);
            }
        }
        
        internal static string Match_Index_Champion {
            get {
                return ResourceManager.GetString("Match_Index_Champion", resourceCulture);
            }
        }
        
        internal static string Match_Index_UsersList {
            get {
                return ResourceManager.GetString("Match_Index_UsersList", resourceCulture);
            }
        }
        
        internal static string Match_Index_Operate {
            get {
                return ResourceManager.GetString("Match_Index_Operate", resourceCulture);
            }
        }
        
        internal static string 查看报名 {
            get {
                return ResourceManager.GetString("查看报名", resourceCulture);
            }
        }
        
        internal static string 详细信息 {
            get {
                return ResourceManager.GetString("详细信息", resourceCulture);
            }
        }
        
        internal static string 比赛介绍 {
            get {
                return ResourceManager.GetString("比赛介绍", resourceCulture);
            }
        }
        
        internal static string Match_Index_Join {
            get {
                return ResourceManager.GetString("Match_Index_Join", resourceCulture);
            }
        }
        
        internal static string Match_Index_Exit {
            get {
                return ResourceManager.GetString("Match_Index_Exit", resourceCulture);
            }
        }
        
        internal static string 用户总分 {
            get {
                return ResourceManager.GetString("用户总分", resourceCulture);
            }
        }
        
        internal static string 成功 {
            get {
                return ResourceManager.GetString("成功", resourceCulture);
            }
        }
        
        internal static string 失败 {
            get {
                return ResourceManager.GetString("失败", resourceCulture);
            }
        }
        
        internal static string 删除 {
            get {
                return ResourceManager.GetString("删除", resourceCulture);
            }
        }
        
        internal static string 时间 {
            get {
                return ResourceManager.GetString("时间", resourceCulture);
            }
        }
        
        internal static string 加入玩家 {
            get {
                return ResourceManager.GetString("加入玩家", resourceCulture);
            }
        }
        
        internal static string 创建人 {
            get {
                return ResourceManager.GetString("创建人", resourceCulture);
            }
        }
        
        internal static string 备注 {
            get {
                return ResourceManager.GetString("备注", resourceCulture);
            }
        }
        
        internal static string 得分 {
            get {
                return ResourceManager.GetString("得分", resourceCulture);
            }
        }
        
        internal static string 创建人_创建时间_结束时间 {
            get {
                return ResourceManager.GetString("创建人/创建时间/结束时间", resourceCulture);
            }
        }
        
        internal static string 发送 {
            get {
                return ResourceManager.GetString("发送", resourceCulture);
            }
        }
        
        internal static string 查看全部 {
            get {
                return ResourceManager.GetString("查看全部", resourceCulture);
            }
        }
        
        internal static string 聊天内容 {
            get {
                return ResourceManager.GetString("聊天内容", resourceCulture);
            }
        }
        
        internal static string 种族名称 {
            get {
                return ResourceManager.GetString("种族名称", resourceCulture);
            }
        }
        
        internal static string 排名 {
            get {
                return ResourceManager.GetString("排名", resourceCulture);
            }
        }
        
        internal static string 总得分 {
            get {
                return ResourceManager.GetString("总得分", resourceCulture);
            }
        }
        
        internal static string 分差 {
            get {
                return ResourceManager.GetString("分差", resourceCulture);
            }
        }
        
        internal static string 裸分 {
            get {
                return ResourceManager.GetString("裸分", resourceCulture);
            }
        }
        
        internal static string 科技得分 {
            get {
                return ResourceManager.GetString("科技得分", resourceCulture);
            }
        }
        
        internal static string 终局计分1 {
            get {
                return ResourceManager.GetString("终局计分1", resourceCulture);
            }
        }
        
        internal static string 终局计分2 {
            get {
                return ResourceManager.GetString("终局计分2", resourceCulture);
            }
        }
        
        internal static string 建筑数量 {
            get {
                return ResourceManager.GetString("建筑数量", resourceCulture);
            }
        }
    }
}
